---
image:
  - Visual Studio 2022
  - Ubuntu
version: 3.1.0.{build}
environment:
  GITHUB_ACTOR: kumaryu
  GITHUB_CR_TOKEN:
    secure: 4ZKkbwwriImTNatsCmqVWNFOsObxDOfbenDzznEtCtfwqqOctigBAOvgbwM9Ll9c
configuration: Release

for:
- matrix:
    only:
      - image: Visual Studio 2019

  install:
  - cmd: |-
      set PATH=C:\Ruby27-x64\bin;%PATH%

  before_build:
  - cmd: |-
      ruby bumpversion.rb %APPVEYOR_BUILD_VERSION%
      docker run --rm --volume="%CD%:/srv/jekyll" -t jekyll/jekyll jekyll build --config doc/help/_config.yml -s doc/help -d PeerCastStation/PeerCastStation.UI.HTTP/help
      dotnet restore PeerCastStation/PeerCastStation.sln

  build_script:
  - cmd: |-
      msbuild -p:Configuration=%CONFIGURATION% -p:"Platform=Any CPU" PeerCastStation/PeerCastStation.sln
      dotnet publish -c %CONFIGURATION% --self-contained -r win-x64 -o win-x64 PeerCastStation/PeerCastStation/PeerCastStation.csproj
      dotnet publish -c %CONFIGURATION% --self-contained -r win-x64 -o win-x64 PeerCastStation/PecaStationd/PecaStationd.csproj
      dotnet publish -c %CONFIGURATION% --self-contained -r win-x86 -o win-x86 PeerCastStation/PeerCastStation/PeerCastStation.csproj
      dotnet publish -c %CONFIGURATION% --self-contained -r win-x86 -o win-x86 PeerCastStation/PecaStationd/PecaStationd.csproj
      dotnet publish -c %CONFIGURATION% --self-contained -r linux-x64 -o linux-x64 PeerCastStation/PeerCastStation/PeerCastStation.csproj -p:PeerCastUseGUI=false
      dotnet publish -c %CONFIGURATION% --self-contained -r linux-arm -o linux-arm PeerCastStation/PeerCastStation/PeerCastStation.csproj -p:PeerCastUseGUI=false
      dotnet publish -c %CONFIGURATION% --self-contained -r linux-arm64 -o linux-arm64 PeerCastStation/PeerCastStation/PeerCastStation.csproj -p:PeerCastUseGUI=false
      dotnet publish -c %CONFIGURATION% --self-contained -r linux-musl-x64 -o linux-musl-x64 PeerCastStation/PeerCastStation/PeerCastStation.csproj -p:PeerCastUseGUI=false
      dotnet publish -c %CONFIGURATION% --self-contained -r linux-musl-arm -o linux-musl-arm PeerCastStation/PeerCastStation/PeerCastStation.csproj -p:PeerCastUseGUI=false
      dotnet publish -c %CONFIGURATION% --self-contained -r linux-musl-arm64 -o linux-musl-arm64 PeerCastStation/PeerCastStation/PeerCastStation.csproj -p:PeerCastUseGUI=false
      dotnet publish -c %CONFIGURATION% --self-contained -r linux-musl-arm64 -o linux-musl-arm64 PeerCastStation/PeerCastStation/PeerCastStation.csproj -p:PeerCastUseGUI=false
      dotnet publish -c %CONFIGURATION% --self-contained -r linux-musl-arm64 -o linux-musl-arm64 PeerCastStation/PeerCastStation/PeerCastStation.csproj -p:PeerCastUseGUI=false
      dotnet publish -c %CONFIGURATION% --no-self-contained -r any -o any PeerCastStation/PeerCastStation/PeerCastStation.csproj -p:PeerCastUseGUI=false

  test_script:
    - dotnet test "PeerCastStation/PeerCastStation.Test/PeerCastStation.Test.fsproj" -c %CONFIGURATION% 

  artifacts:
  - path: win-x64
    name: PeerCastStation-win-x64-$(APPVEYOR_BUILD_VERSION)
  - path: win-x86
    name: PeerCastStation-win-x86-$(APPVEYOR_BUILD_VERSION)
  - path: linux-x64
    name: PeerCastStation-linux-x64-$(APPVEYOR_BUILD_VERSION)
  - path: linux-arm
    name: PeerCastStation-linux-arm-$(APPVEYOR_BUILD_VERSION)
  - path: linux-arm64
    name: PeerCastStation-linux-arm64-$(APPVEYOR_BUILD_VERSION)
  - path: linux-musl-x64
    name: PeerCastStation-linux-musl-x64-$(APPVEYOR_BUILD_VERSION)
  - path: linux-musl-arm
    name: PeerCastStation-linux-musl-arm-$(APPVEYOR_BUILD_VERSION)
  - path: linux-musl-arm64
    name: PeerCastStation-linux-musl-arm64-$(APPVEYOR_BUILD_VERSION)
  - path: any
    name: PeerCastStation-any-$(APPVEYOR_BUILD_VERSION)
  - path: PeerCastStation/PecaStationdInstaller/bin/$(CONFIGURATION)/PecaStationd-$(APPVEYOR_BUILD_VERSION).msi
    name: PecaStationd-$(APPVEYOR_BUILD_VERSION).msi
  - path: PeerCastStation/SetupBundle/bin/$(CONFIGURATION)/PeerCastStation-$(APPVEYOR_BUILD_VERSION).exe
    name: PeerCastStation-$(APPVEYOR_BUILD_VERSION).exe

- matrix:
    only:
      - image: Ubuntu

  install:
    - rvm use 2.7

  before_build:
    - echo $PWD
    - echo `pwd`
    - ruby bumpversion.rb $APPVEYOR_BUILD_VERSION
    - docker run --rm --volume=`pwd`:/srv/jekyll -t jekyll/jekyll jekyll build --config doc/help/_config.yml -s doc/help -d PeerCastStation/PeerCastStation.UI.HTTP/help

  build_script:
    - docker build --rm -t ghcr.io/$GITHUB_ACTOR/peercaststation:$APPVEYOR_BUILD_VERSION -f PeerCastStation/PeerCastStation/Dockerfile PeerCastStation/
    - docker build --rm -t ghcr.io/$GITHUB_ACTOR/peercaststation:$APPVEYOR_BUILD_VERSION-test -f PeerCastStation/PeerCastStation/Dockerfile PeerCastStation/ --target test
    - docker save -o peercaststation-$APPVEYOR_BUILD_VERSION.tar ghcr.io/$GITHUB_ACTOR/peercaststation:$APPVEYOR_BUILD_VERSION

  test_script:
    - docker run -t --rm ghcr.io/$GITHUB_ACTOR/peercaststation:$APPVEYOR_BUILD_VERSION-test

  deploy_script:
    - echo $GITHUB_CR_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - docker push ghcr.io/$GITHUB_ACTOR/peercaststation:$APPVEYOR_BUILD_VERSION

  artifacts:
    - path: peercaststation-$(APPVEYOR_BUILD_VERSION).tar

